url: https://jakelisby.github.com

# Site settings
title: Rain Tomorrow Design
email: jakelisby@gmail.com
description: "CREATIVE SOLUTIONS FOR YOUR EVOLVING BUSINESS"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0b3659
  secondary: 6cb8c6  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Jake Lisby
  pic: 1
  position: CEO, Designer/Developer
  social:
    - title: twitter
      url: http://twitter.com/jakelisby
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jakelisby
  - title: github
    url: http://github.com/jakelisby

# Postal address (add as many lines as necessary)
address:
  - line: Kansas City, MO 64068

# Build settings
markdown: kramdown
permalink: pretty